language: c

os:
  - linux
  - osx

compiler:
  - gcc

env:
    - CONFIGURE_ARGS='-Uusethreads'
    - CONFIGURE_ARGS='-Dusethreads'

script:
  - ./Configure -des -Dusedevel -Uversiononly -Dcc=$CC $CONFIGURE_ARGS -Dprefix=$HOME/perl-blead -DDEBUGGING && TEST_JOBS=8 make -j8 test_harness_notty && make -j8 install && $HOME/perl-blead/bin/perlivp

addons:
    apt:
        packages:
            - file
            - cpio
            - libdb-dev
            - libgdbm-dev
            - zlib1g-dev
            - libbz2-dev
